DLS-9277 - preventing duplicate returns
hmrc/cgt-property-disposals-frontend pull request #1250
Opened 2023-11-14 14:27 UTC by TomRafferty

2023-11-15 10:34 UTC, johno1985 reviewed
you'll need to modify the unit tests and fix the failing PR build

2023-11-20 15:05 UTC, TomRafferty commented
rebuild

2023-11-21 10:32 UTC, johno1985 commented
PR build failed

2023-11-21 11:20 UTC, johno1985 commented on app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/StartController.scala
> +      case _ =>
I would remove this for now, just keep the extra case above

2023-11-21 11:21 UTC, johno1985 requested changes
comment added

2023-11-21 11:30 UTC, TomRafferty commented
rebuild

2023-11-21 14:59 UTC, johno1985 approved these changes

2023-11-23 11:27 UTC, merged