DLS-9277 | Handle duplicate returns
hmrc/cgt-property-disposals-frontend pull request #1261
Opened 2023-11-29 08:42 UTC by mahesh-hmrc

Introduce new subscription state, `SubmittingReturn`,  to avoid duplicate returns.

2023-11-29 10:04 UTC, johno1985 requested changes
We are still missing the handling in the HomePageController, otherwise infinite redirects will occur

2023-11-29 14:42 UTC, johno1985 commented
rebuild

2023-11-30 12:12 UTC, TomRafferty commented
rebuild

2023-11-30 12:13 UTC, TomRafferty commented
These intermittent failures need addressing ASAP

2023-11-30 12:33 UTC, johno1985 commented
rebuild

2023-11-30 15:42 UTC, merged